---
title: "nata-boxplots"
author: "Kara E. McCormack"
date: "11/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries
library(PReMiuM)
library(stringr)
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
# set up paths
data.dir = "/Users/karamccormack/Box/SES-environment/Spatial LCM Paper/Data/"
output.dir = "/Users/karamccormack/Box/SES-environment/Spatial LCM Paper/Output/"

# original data
NC_df <- read_csv(file.path(data.dir, "NC_NATA_wide_total_conc.csv"))[,-1]

# load z-transformed NC NATA data (mean)
NC_df_z = read.csv(file.path(data.dir, "NC_NATA_wide_z_transform.csv"))[,-1]

# load log-transformed NC NATA data
NC_df_log = read.csv(file.path(data.dir, "NC_NATA_wide_log_transform.csv"))[,-1]


```

```{r}
# original data
# wide to long
# Make sure the subject column is a factor
# undo log transformation
NC_df$Tract <- factor(NC_df$Tract)
NC_df_long <- NC_df %>%
  gather(Pollutant,
         Level,
         X1.3.BUTADIENE:XYLENES_.MIXED_ISOMERS.) %>% # keep the cluster column - need this for plotting
  mutate(Pollutant = tolower(str_replace_all(Pollutant, "_", " "))) 

# note, this still has cluster in it. This is the data where I
# put the clusters on it (result from bayesian profile regression)
# can ignore cluster column for boxplots plotting
```

```{r}
# join with type
# boxplots for original data
# add on type variable
# need to make "Pollutant" names match those of poln_vrbs$nms
# rename three pollutants who still don't match
NC_df_long[NC_df_long$Pollutant == "x1.3.butadiene",]$Pollutant <- "1,3-butadiene"
NC_df_long[NC_df_long$Pollutant == "methyl chloride .chloromethane.",]$Pollutant <- "methyl chloride"
NC_df_long[NC_df_long$Pollutant == "xylenes .mixed isomers.",]$Pollutant <- "xylenes"

# make sure names match
unique(NC_df_long$Pollutant) == poln_vrbs$nms

# prep for left join
poln = poln_vrbs[,c("nms", "type")]
colnames(poln)[1] <- "Pollutant"
poln$Pollutant <- as.character(poln$Pollutant)

# left join with type
NC_df_long = NC_df_long %>%
  left_join(poln) 

head(NC_df_long)
```

```{r}
# boxplot for original data
p <- ggplot(NC_df_long, aes(x=Pollutant, y=Level, fill = type)) + 
  geom_boxplot() + 
  ggtitle("Boxplots of Raw Pollutant Variables")
p
```


```{r}
# add on type variable
# need to make "Pollutant" names match those of poln_vrbs$nms
# rename three pollutants who still don't match
NC_df_long[NC_df_long$Pollutant == "x1.3.butadiene",]$Pollutant <- "1,3-butadiene"
NC_df_long[NC_df_long$Pollutant == "methyl chloride .chloromethane.",]$Pollutant <- "methyl chloride"
NC_df_long[NC_df_long$Pollutant == "xylenes .mixed isomers.",]$Pollutant <- "xylenes"

# make sure names match
unique(NC_df_long$Pollutant) == poln_vrbs$nms

# prep for left join
poln = poln_vrbs[,c("nms", "type")]
colnames(poln)[1] <- "Pollutant"
poln$Pollutant <- as.character(poln$Pollutant)

# left join with type
NC_df_long = NC_df_long %>%
  left_join(poln) 
```

