---
title: "nata-simulations"
author: "Kara E. McCormack"
date: "11/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries
library(PReMiuM)
library(stringr)
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
# set up paths
data.dir = "/Users/karamccormack/Box/SES-environment/Spatial LCM Paper/Data/"
output.dir = "/Users/karamccormack/Box/SES-environment/Spatial LCM Paper/Output/"

# load original NC NATA data
NC_df <- read_csv(file.path(data.dir, "NC_NATA_wide_total_conc.csv"))[,-1]
# load z-transformed NC NATA data
NC_df_z = read.csv(file.path(data.dir,"NC_NATA_wide_z_transform.csv"))[,-1]

colnames(NC_df_z) <- colnames(NC_df)
# need no spaces in pollutant names to plug into profile regression
colnames(NC_df_z) <- str_replace_all(colnames(NC_df_z)," " , "_")

# define covariate names
covariate_names <- colnames(NC_df_z)[-1]
```

```{r}
# Beta Plot 1
# Goal: assess convergence of variable beta 
# Specifications:
# nSweeps: 100000
# nBurn: 10000
# data: z-transformed data ((value-mean)/sd)
# nClusInit = 30

# set working directory for output files
setwd("/Users/karamccormack/Box/SES-environment/Spatial LCM Paper/v2/spatial-mpe-ses/output/scratch/Beta_1")
# run profile regression
runInfoObj_beta1 <- profRegr(yModel = "Normal",
        xModel = "Normal",
        nSweeps = 100000,
        nBurn = 10000,
        data = NC_df_z,
        output = "output",
        covNames = covariate_names,
        nClusInit = 30,
        whichLabelSwitch="123",
        run = TRUE,
        excludeY = TRUE, 
        seed = 1234)

# plotting to assess convergence of beta
# (red plot)
globalParsTrace(runInfoObj_beta1, 
                parameters = "beta",
                plotBurnIn = FALSE, 
                whichBeta = 1)
# autocorrelation plot
# requires "coda" library
install.packages("coda")
library(coda)
betaChain <- mcmc(read.table("output_beta.txt")[,1])
autocorr.plot(betaChain)

# how many clusters?
# calculate dissimilarity matrix
dissimObj_beta1 = calcDissimilarityMatrix(runInfoObj_beta1)
clusObj_beta1 = calcOptimalClustering(beta1)
table(clusObj_beta1$clustering)

```


```{r}
# Simulation 1

# set working directory where output files will go
setwd("/Users/karamccormack/Box/SES-environment/Spatial LCM Paper/v2/spatial-mpe-ses/output/scratch/Simulation1")

# create vector of initial number of clusters
nclusinit = c(5, 7, 10, 20, 40, 50)
# initiate empty list for results
result = list()

for (i in 1:length(nclusinit)){
  paste0("runinfo_", nclusinit[i], "clusInit", "_sim1") <- profRegr(yModel = "Normal",
        xModel = "Normal",
        nSweeps = 100000,
        nBurn = 10000,
        data = NC_df_z,
        output = paste0("output", nclusinit[i], "init", "_sim1_"),
        covNames = covariate_names,
        nClusInit = nclusinit[i],
        whichLabelSwitch="123",
        run = TRUE,
        excludeY = TRUE, 
        seed = 1234)
  paste0("disSimObj", nclusinit[i], "clusInit", "_sim1_") <- paste0("runinfo_", nclusinit[i], "clusInit")
  y <- calcDissimilarityMatrix(x)
  z <- calcOptimalClustering(y)
  result[[i]] <- z$clustering
  print("Initial clusters = ", nclusinit[i], " gives ", length(unique(z$clustering)), " final clusters. ")

}
```



